name: Lint Markdown Docs

on: [push, pull_request]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run MarkdownLint
        uses: DavidAnson/markdownlint-cli2-action@v5
